### ISSUE TITLE
Running application without raspberry support returns error: cannot load such file -- rpi_gpio (LoadError)

### ISSUE THREAD

**Issue by yapsr** [ciembor/dobra-noc#19]
I am trying to install this application, without raspberry pi support.

When running `bundle exec rails db:migrate` I get this error:

```
#<Thread:0x0000559ad00a5058@/dobra-noc/config/initializers/sonometer.rb:3 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- rpi_gpio (LoadError)
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:289:in `block in load_dependency'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:702:in `new_constants_in'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:289:in `load_dependency'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
	from /dobra-noc/app/services/raspberry.rb:1:in `<main>'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:511:in `block in load_file'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:702:in `new_constants_in'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:510:in `load_file'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:407:in `block in require_or_load'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:40:in `block in load_interlock'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:40:in `load_interlock'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:390:in `require_or_load'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:545:in `load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:214:in `const_missing'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:582:in `load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:214:in `const_missing'
	from /dobra-noc/app/jobs/sonometer_listener_job.rb:7:in `perform'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/execution.rb:39:in `block in perform_now'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
	from /usr/local/bundle/ruby/2.6.0/gems/i18n-1.7.0/lib/i18n.rb:292:in `with_locale'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `instance_exec'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `instance_exec'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `block in instrument'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `instrument'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/logging.rb:45:in `block in tag_logger'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:28:in `tagged'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80:in `tagged'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/logging.rb:45:in `tag_logger'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `instance_exec'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/execution.rb:38:in `perform_now'
	from /usr/local/bundle/ruby/2.6.0/gems/activejob-6.0.1/lib/active_job/execution.rb:18:in `perform_now'
	from /dobra-noc/config/initializers/sonometer.rb:4:in `block in <main>'
Bootsnap::LoadPathCache::FallbackScan
```

How to solve this?

**Comment by yapsr** [comment]
I have solved this temporarily by changing these lines in `sonometer_listener_job.rb`:

```is_raspberry = Raspberry.is_raspberry?```
to
```is_raspberry = false```

Is this a bug? Or should I use a different command to start the application without raspberry support?
